services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql-data/db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080